import '@/app/globals.css'
import {auth} from '@/lib/auth'
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import Provider from '@/contexts/client-provider'
import React from "react";
import {AuthProvider} from "@/contexts/user-provider";
import ToastProvider from "@/contexts/toast-provider";
import Footer from "@/components/ui/footer/footer";

const font = Poppins({subsets: ['latin'], weight: "400"});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
                                           children,
                                         }: {
  children: React.ReactNode
}) {

  return (
    // <Provider session={session}>
      <AuthProvider>
        <html lang="en">
        <body className={font.className}>
        <ToastProvider>
          {children}
          <Footer/>
        </ToastProvider>
        </body>
        </html>
      </AuthProvider>
    // </Provider>

  )
}
